// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {sshterm} from '../models';

export function BatchImport(arg1:Array<store.Server>):Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function Connect(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<string>;

export function CreateServer(arg1:store.Server):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function ListServers():Promise<Array<store.Server>>;

export function ListSessions():Promise<Array<string>>;

export function SFTPDownload(arg1:string,arg2:string):Promise<Array<number>>;

export function SFTPDownloadDialog(arg1:string,arg2:string):Promise<void>;

export function SFTPList(arg1:string,arg2:string):Promise<Array<sshterm.FileEntry>>;

export function SFTPMkdir(arg1:string,arg2:string):Promise<void>;

export function SFTPRead(arg1:string,arg2:string):Promise<string>;

export function SFTPRemove(arg1:string,arg2:string):Promise<void>;

export function SFTPRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPUpload(arg1:string,arg2:string,arg3:string,arg4:Array<number>):Promise<void>;

export function SFTPUploadChunk(arg1:string,arg2:string,arg3:string,arg4:Array<number>,arg5:boolean):Promise<void>;

export function SFTPWrite(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TerminalInput(arg1:string,arg2:string):Promise<void>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function UpdateServer(arg1:store.Server):Promise<void>;
