// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchImport(arg1) {
  return window['go']['main']['App']['BatchImport'](arg1);
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function Connect(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4, arg5);
}

export function ConnectServer(arg1) {
  return window['go']['main']['App']['ConnectServer'](arg1);
}

export function ConnectServerWithPassphrase(arg1, arg2) {
  return window['go']['main']['App']['ConnectServerWithPassphrase'](arg1, arg2);
}

export function CopyServer(arg1) {
  return window['go']['main']['App']['CopyServer'](arg1);
}

export function CreateServer(arg1) {
  return window['go']['main']['App']['CreateServer'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DeleteHostKey(arg1) {
  return window['go']['main']['App']['DeleteHostKey'](arg1);
}

export function ListHostKeys() {
  return window['go']['main']['App']['ListHostKeys']();
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function SFTPDownloadDialog(arg1, arg2) {
  return window['go']['main']['App']['SFTPDownloadDialog'](arg1, arg2);
}

export function SFTPList(arg1, arg2) {
  return window['go']['main']['App']['SFTPList'](arg1, arg2);
}

export function SFTPMkdir(arg1, arg2) {
  return window['go']['main']['App']['SFTPMkdir'](arg1, arg2);
}

export function SFTPRead(arg1, arg2) {
  return window['go']['main']['App']['SFTPRead'](arg1, arg2);
}

export function SFTPRemove(arg1, arg2) {
  return window['go']['main']['App']['SFTPRemove'](arg1, arg2);
}

export function SFTPStat(arg1, arg2) {
  return window['go']['main']['App']['SFTPStat'](arg1, arg2);
}

export function SFTPRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPRename'](arg1, arg2, arg3);
}

export function SFTPUpload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SFTPUpload'](arg1, arg2, arg3, arg4);
}

export function SFTPUploadChunk(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SFTPUploadChunk'](arg1, arg2, arg3, arg4, arg5);
}

export function SFTPWrite(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPWrite'](arg1, arg2, arg3);
}

export function TerminalInput(arg1, arg2) {
  return window['go']['main']['App']['TerminalInput'](arg1, arg2);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function UpdateServer(arg1) {
  return window['go']['main']['App']['UpdateServer'](arg1);
}

export function UpdateServerPreserveSecrets(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateServerPreserveSecrets'](arg1, arg2, arg3);
}
